FIRST_NAME = '#firstname'
LAST_NAME = '#lastname'
EMAIL = 'input[title="Email"]'
PWD = 'input[title="Password"]'
CONFIRM_PWD = 'input[title="Confirm Password"]'
CREATE_ACCOUNT_BTN = 'button[title="Create an Account"]'
SUCCESS_MSG = '//*[text()="Thank you for registering with Main Website Store."]'
CREATED_ACC = 'li.greet.welcome'
FIRST_NAME_ERROR = '#firstname-error'
LAST_NAME_ERROR = '#lastname-error'
EMAIL_ERROR = '#email_address-error'
PWD_ERROR = '#password-error'
PWD_CONFIRM_ERROR = '#password-confirmation-error'
