LINK_PAGE = "newoffer"
BRAND = "Suzuki"
SECTION = 1
TYPE = "Седан"
PRICE = 15000
CURRENCY = "EUR"
MONTH = "февруари"
YEAR = 2010
MODEL = "Reno"
ENGINE_TYPE = "Хибриден"
GEARBOX = "Ръчна"
REGION = "Варна"
PLACE = "гр. Варна"
MILEAGE = 150000
INVALID_MESSAGE_STATUS = 'Некоректна стойност в "Състояние"!'
INVALID_MESSAGE_LETTER_FORMAT = 'Пишете на кирилица и с малки букви в "Допълнителна информация"!'
TITLE_BIG = "Публикуване на безплатна обява"
TEXT_ADD_INFO = "GHHRRRRRRccvvbb"
USED_CHECKBOX = 0
PARTS_CHECKBOX = 2
POSTFIX = "promote"
POSTFIX_NEW_OFFER = "newoffer"
