name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        type: choice
        required: true
        default: smoke
        options:
          - all
          - regression
          - smoke

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run Tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run all tests
        run: cd selenium_tests_eokulik && pytest -v
