name: Run autotests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: select tests to run
        type: choice
        required: true
        default: smoke
        options:
          - all
          - regression
          - smoke

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: run Tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4
      - name: Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'all'"
        run: cd selenium_tests_eokulik && pytest -v --alluredir=results
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'smoke'"
        run: cd selenium_tests_eokulik && pytest -v -m smoke --alluredir=results
      - name: Run regression tests
        if: "github.event.inputs.deployment_target == 'regression'"
        run: cd selenium_tests_eokulik && pytest -v -m regression --alluredir=results
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '17'
      - name: Install Allure
        run: |
          sudo wget https://github.com/allure-framework/allure2/releases/download/2.32.0/allure-2.32.0.tgz && 
          sudo tar -zxvf allure-2.29.0.tgz -C /opt/ && 
          sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
      - name: Generate report
        run: allure generate -c results -o Report
      - name: Save report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: Report
          path: Report
          retention-days: 1
