FIRST_NAME = '#firstname'
SECOND_NAME = '#lastname'
EMAIL = '#email_address'
PASSWORD = '#password'
CONFIRM_PASSWORD = '#password-confirmation'
CREATE_ACCOUNT_BUTTON = '//*[@id="form-validate"]/div/div[1]/button'
SUCCESS_MESSAGE = '//*[text()="Thank you for registering with Main Website Store."]'
EMAIL_ERROR = '#email_address-error'
CONFIRM_PASSWORD_ERROR = '#password-confirmation-error'
